### ISSUE TITLE
Remove Gulp-Util Dependancy - Gulp 4.0

### ISSUE THREAD

**Issue by tommyc38** [trygve-lie/gulp-dom#113]
gulp 4 has deprecated gulp-util which is one of your dependencies.  Can you please update this package?  See this [medium article](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5).

**Comment by trygve-lie** [comment]
Should be fixed by this: https://github.com/trygve-lie/gulp-dom/pull/115
